apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: python-starter-project
    version: v1
  name: python-starter-project-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      run: python-starter-project
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: python-starter-project
        version: v1
    spec:
      containers:
      - name: python-starter-project
        image: python-starter-project:v1
        env: []
        livenessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          httpGet:
            path: /ping
            port: http
        readinessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 5
          httpGet:
            path: /ping
            port: http
        ports:
        - name: http
          containerPort: 8080
      restartPolicy: Always
