apiVersion: v1
kind: Service
metadata:
  name: python-starter-project-v1
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    run: python-starter-project
    version: v1
  type: ClusterIP
