FROM tiangolo/uwsgi-nginx-flask:python2.7-alpine3.7

COPY ./app /app

# Copy config files
COPY ./resources/nginx/nginx.conf /etc/nginx/conf.d/

# Install requirements
# Note that changing requirements.txt will trigger a rebuild every time
# To avoid this, add pip install commands here line by line

WORKDIR /app
RUN pip install -U setuptools pip
RUN apk update && apk add bash

# Expose ports
EXPOSE 9090 9191

# Place any commands here
#CMD ["python", "test_app.py"]
#CMD ["./launch_server.sh"]